//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _360LawGroup.CostOfSalesBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminSetting
    {
        public string ParamName { get; set; }
        public string ParamTitle { get; set; }
        public string ParamValue { get; set; }
        public string ParamType { get; set; }
    }
}
