//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _360LawGroup.CostOfSalesBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.ClientFiles = new HashSet<ClientFile>();
            this.ClientIncomes = new HashSet<ClientIncome>();
            this.ConsultantCosts = new HashSet<ConsultantCost>();
            this.ConsultantHours = new HashSet<ConsultantHour>();
            this.Matters = new HashSet<Matter>();
        }
    
        public System.Guid Id { get; set; }
        public string Company { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string JobTitle { get; set; }
        public string BusinessPhone { get; set; }
        public string FaxNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLIne2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string ContractedCountries { get; set; }
        public Nullable<System.DateTime> ContractRenewalDate { get; set; }
        public string Notes { get; set; }
        public string Attechments { get; set; }
        public bool IsSubscription { get; set; }
        public string SubscriptionBasis { get; set; }
        public Nullable<decimal> MonthlySubscription { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public string SubscriptionType { get; set; }
        public string PaymentMonths { get; set; }
        public Nullable<decimal> MemberChargeRate { get; set; }
        public Nullable<decimal> PrivateClientChargeRate { get; set; }
        public Nullable<decimal> LitigationChargeRate { get; set; }
        public Nullable<decimal> RegulatedChargeRate { get; set; }
        public Nullable<decimal> SPAREChargeRate { get; set; }
        public bool InWorkThisMonth { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<decimal> SubscriptionCharge { get; set; }
        public Nullable<System.DateTime> NextSubscriptionDate { get; set; }
        public Nullable<int> NextSubMonth { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string FullName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientFile> ClientFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientIncome> ClientIncomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultantCost> ConsultantCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultantHour> ConsultantHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matter> Matters { get; set; }
    }
}
