//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _360LawGroup.CostOfSalesBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFile
    {
        public System.Guid Id { get; set; }
        public System.Guid ClientId { get; set; }
        public string Category { get; set; }
        public string Files { get; set; }
        public string Image { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
