//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _360LawGroup.CostOfSalesBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultantCost
    {
        public System.Guid Id { get; set; }
        public System.Guid Matter_Consultant_WorkPeriod { get; set; }
        public System.Guid MatterId { get; set; }
        public System.Guid ClientId { get; set; }
        public System.Guid WorkRateId { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<decimal> MonNum { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string ClientWorkPeriod { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<decimal> SubscriptionCost { get; set; }
        public Nullable<decimal> MemberCost { get; set; }
        public Nullable<decimal> PrivateClientCost { get; set; }
        public Nullable<decimal> LitigationCost { get; set; }
        public Nullable<decimal> RegulatedCost { get; set; }
        public Nullable<decimal> OverseasCost { get; set; }
        public Nullable<decimal> Cost_incl_Sub { get; set; }
        public Nullable<decimal> Cost_excl_Sub { get; set; }
        public string Status { get; set; }
        public string DisbursementDescription { get; set; }
        public Nullable<decimal> DisbursementAmount { get; set; }
        public Nullable<decimal> RateUsed { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ConsultantHour ConsultantHour { get; set; }
        public virtual Matter Matter { get; set; }
        public virtual WorkRate WorkRate { get; set; }
    }
}
