//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _360LawGroup.CostOfSalesBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultant
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string UserStatus { get; set; }
        public string ConsultantCompany { get; set; }
        public string EmailAddress_360BusinessLaw { get; set; }
        public string EmailAddress_PrivateClientLaw { get; set; }
        public string EmailAddress_360LawServices { get; set; }
        public string PrivateEmailAddress { get; set; }
        public string AreaofLaw { get; set; }
        public string BusinessPhone { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Address { get; set; }
        public string JurisdictionsCovered { get; set; }
        public string Notes { get; set; }
        public string Attachments { get; set; }
        public Nullable<decimal> SubscriptionHourlyRate { get; set; }
        public Nullable<decimal> MemberHourlyRate { get; set; }
        public Nullable<decimal> PrivateClientHourlyRate { get; set; }
        public Nullable<decimal> LitigationHourlyRate { get; set; }
        public Nullable<decimal> RegulatedHourlyRate { get; set; }
        public Nullable<decimal> OverseasHourlyRate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string ConsultantName { get; set; }
    }
}
