//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _360LawGroup.CostOfSalesBilling.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminSetting> AdminSettings { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ClientFile> ClientFiles { get; set; }
        public virtual DbSet<ClientIncome> ClientIncomes { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ConsultantCost> ConsultantCosts { get; set; }
        public virtual DbSet<ConsultantHour> ConsultantHours { get; set; }
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<Matter> Matters { get; set; }
        public virtual DbSet<ResetNewMonth> ResetNewMonths { get; set; }
        public virtual DbSet<WorkRate> WorkRates { get; set; }
    }
}
