//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _360LawGroup.CostOfSalesBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matter()
        {
            this.ConsultantCosts = new HashSet<ConsultantCost>();
            this.ConsultantHours = new HashSet<ConsultantHour>();
            this.Consultants = new HashSet<Consultant>();
        }
    
        public System.Guid Id { get; set; }
        public string MatterName { get; set; }
        public System.Guid ClientId { get; set; }
        public System.Guid WorkRateId { get; set; }
        public string WorkRateChoice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool CurrentMonth { get; set; }
        public string AreaofLaw { get; set; }
        public string Status { get; set; }
        public string Box { get; set; }
        public Nullable<bool> Overseas { get; set; }
        public string OverseasCountry { get; set; }
        public Nullable<decimal> OverseasChargeRate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<bool> Billable { get; set; }
        public long Number { get; set; }
        public string ClientMatterContact { get; set; }
        public string ClientMatter_ContactEmail { get; set; }
        public Nullable<int> MonNum { get; set; }
        public string MonthName { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultantCost> ConsultantCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultantHour> ConsultantHours { get; set; }
        public virtual WorkRate WorkRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultant> Consultants { get; set; }
    }
}
